version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

# Location of the conf.py
sphinx:
  configuration: docs/source/conf.py

# Conda environment
conda:
  environment: docs/source/environment.yml

