version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"

# Location of the conf.py
sphinx:
  configuration: docs/conf.py

# Conda environment
conda:
  environment: docs/requirements.yml
