package:
  name: grandlig
  version: "1.0.0"

source:
  path: ..

build:
  number: 0
  noarch: python
  script:
    - mkdir -p $PREFIX/site-packages
    - cp -r $RECIPE_DIR/../grandlig $PREFIX/site-packages/grandlig

requirements:
  build:
    - python>=3.10
    - pytest
    - openmm>=8.0  
  run:
    - lxml
    - openmm>=8.0
    - pip
    - numpy
    - MDAnalysis
    - mdtraj
    - parmed
    - pymbar
    - scipy
    - tqdm
    - openmmtools
    - numba>=0.60

test:
  requires:
    - pytest

about:
  home: https://github.com/essex-lab/grand-lig
  summary: A Python module for carrying out GCNCMC insertions and deletions of small molecules in OpenMM.
  license: MIT

