name: docs_grandlig
channels:
  - defaults
dependencies:
# Base depends
- python
- pip
- sphinx<7
- sphinx-click
- gitpython
- tqdm
- libsass
- nbsphinx
- nbsphinx-link
- myst-parser
- numpy
- MDAnalysis
- mdtraj
- openmm
- parmed
- pymbar
- scipy
- tqdm
- openmmtools
- numba >= 0.60
- pip:
  - -e ../
  - sphinx-design
  - sphinx-toolbox
  - sphinx-copybutton
  - sphinx-rtd-theme
  - sphinx<7

# These are added automatically by RTD, so we include them here 
# for a consistent environment.
- mock
- pillow
- sphinx
- sphinx_rtd_theme
